baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Menus"

sectionPagesMenu = "main"
#contentDir = "content2"


#### accurate only on contentDir = "content"

[[menu.second]]
  name = "lorem"
  title = "Lorem Ipsum"
  url = "/lorem"
  identifier = "lorem"

[[menu.second]]
  name = "About"
  title = "About Menu"
  identifier = "about"
  url = "/about/"

[[menu.second]]
  name = "Animals"
  title = "Animals Menu"
  identifier = "animals"
  url = "/animals/"

[[menu.second]]
  name = "Radiata"
  title = "Radiata Menu"
  identifier = "radiata"
  url = "/animals/eumetazoa/radiata/"
  parent = "animals"

[[menu.second]]
  name = "Bilateria"
  title = "Bilateria Menu"
  identifier = "bilateria"
  url = "/animals/eumetazoa/bilateria/"
  parent = "animals"

[[menu.second]]
  name = "Porifera"
  title = "Porifera Menu"
  identifier = "porifera"
  url = "/animals/parazoa/porifera/"
  parent = "animals"

[[menu.second]]
  name = "Nematoda"
  title = "Nematoda Menu"
  identifier = "nematoda"
  url = "/animals/eumetazoa/bilateria/pseudo-coelomates/nematoda/"
  parent = "bilateria"

[[menu.second]]
  name = "Chordata"
  title = "Chordata Menu"
  identifier = "chordata"
  url = "/animals/eumetazoa/bilateria/coelomates/deuterostomia/chordata/"
  parent = "bilateria"

